[wip] Add support for Sensu enterprise
cmacrae/ansible-sensu pull request #82
Opened 2017-04-13 01:49 UTC by haphan

Todo:  Add support for `sensu-enterprise`for following distributions
- ✅  CentOS/RHEL  
- ➖  Ubuntu

2017-04-13 16:11 UTC, smuth4 requested changes

2017-04-13 16:11 UTC, smuth4 commented on defaults/main.yml
> +dynamic_data_store: "{{ playbook_dir }}/data/store"
Didn't know `playbook_dir` was a thing, 👍

2017-04-13 16:11 UTC, smuth4 commented on tasks/dashboard.yml
> +      name: {{ uchiwa_service_name if not se_enterprise else sensu_enterprise_dashboard_service_name }}
This value needs to be quoted.

2017-04-13 16:11 UTC, smuth4 commented on tasks/common.yml
> -      - restart sensu-client service
`sensu-client` will still need to be restarted for non-enterprise users on all of these (and for enterprise users as well I think?).

2017-04-13 16:11 UTC, smuth4 commented on tasks/server.yml
> +    when: not se_enterprise
Gonna be a stickler and ask for a newline at EOF here 😀

2017-04-13 16:11 UTC, smuth4 commented on defaults/main.yml
> +sensu_rabbitmq_config: sensu-rabbitmq.json.j2
What is this trying to be consistent with? None of the other config files use the `sensu-` prefix.

2017-04-13 16:11 UTC, smuth4 commented on templates/rabbitmq.config.j2
> +    {% if sensu_ssl_manage_certs %}
The `sensu_ssl_manage_certs` was requested specifically by someone that wanted SSL to be used, but didn't want the cert files to be handled by this role. Please use a different variable or get rid of it altogether.

2017-04-13 16:11 UTC, smuth4 commented on templates/sensu-rabbitmq.json.j2
> +    {% if sensu_ssl_manage_certs %}
Same here regarding `sensu_ssl_manage_certs`.

2017-04-17 02:32 UTC, haphan commented on defaults/main.yml
> +sensu_rabbitmq_config: sensu-rabbitmq.json.j2
Sensu related configuration should have prefix `sensu-` as seen in https://github.com/sensu/sensu-ansible/blob/master/tasks/common.yml#L19.

2017-04-17 06:31 UTC, haphan commented on tasks/common.yml
> -      - restart sensu-client service
`sensu-client` service may not exist in sensu master node for enterprise users (`sensu-enterprise` only comprises of `sensu-server` and `sensu-api` [Reference)](https://sensuapp.org/docs/0.28/platforms/sensu-on-rhel-centos.html#sensu-enterprise). 

Restart a non-existing service may fail the playbook. Besides, I don't know if it is a common installation what sensu master will monitor itself as a client.

2017-04-17 06:37 UTC, haphan commented on tasks/common.yml
> -      - restart sensu-client service
What do you think of a new variable `sensu_client` to deploy sensu client? @smuth4

2017-04-19 03:30 UTC, smuth4 commented
👍 to the update, the only things remaining are the `sensu_ssl_manage_certs` thing and a rebase (should only be documentation changes I think).

2017-04-26 10:29 UTC, haphan commented
@smuth4  Can you review again? Thanks

2017-04-26 16:14 UTC, smuth4 approved these changes

2017-04-26 16:16 UTC, merged

2017-04-26 16:16 UTC, smuth4 commented
Thanks for all the work!